# SPDX-FileCopyrightText: 2024 Friflex <friflex.com>
# SPDX-License-Identifier: BSD-3-Clause
name: location_aurora
description: The Aurora OS implementation of location_aurora.
version: 1.0.0
publish_to: https://pub-aurora.friflex.com
homepage: "https://github.com/smmarty/aurora_flutter/tree/main/packages/location_aurora"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.13.5"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  location_platform_interface: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  fake_async: ^1.3.1

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: LocationAurora
        pluginClass: LocationAuroraPlugin
