include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  errors:
#   Временный игнор пока не перенесем на паб систему
    invalid_dependency: ignore