name: aurora_safe_area
description: A new Flutter package project.
version: 0.1.0
publish_to: https://pub-aurora.friflex.com
homepage: "https://github.com/smmarty/aurora_flutter/tree/main/packages/aurora_safe_area"

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  flutter_keyboard_visibility_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: d612b55b2cf3b3a8cfbb3ef004460cf8613e66f4
      path: packages/flutter_keyboard_visibility/flutter_keyboard_visibility_aurora
  device_info_plus: ^9.0.3
  device_info_plus_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: d612b55b2cf3b3a8cfbb3ef004460cf8613e66f4
      path: packages/device_info_plus/device_info_plus_aurora
  dbus: ^0.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
