name: safe_area_aurora_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  aurora_safe_area:
    path: ../
  device_info_plus: ^9.0.3
  device_info_plus_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: d612b55b2cf3b3a8cfbb3ef004460cf8613e66f4
      path: packages/device_info_plus/device_info_plus_aurora
  dbus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true