name: vibration_aurora_example
description: Demonstrates how to use the vibration plugin.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.12.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration_aurora:
    path: ../
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
