name: vibration_aurora
description: A plugin for handling Vibration API on Aurora OS
version: 0.1.0
repository: https://github.com/smmarty/aurora_flutter/tree/main/packages/vibration_aurora
homepage: https://pub-aurora.friflex.com/packages/vibration_aurora
publish_to: https://pub-aurora.friflex.com

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      aurora:
        pluginClass: VibrationAuroraPlugin
