name: example
description: Demonstrates how to use the location plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  location: 5.0.3
  location_aurora:
    path: ../
  url_launcher: 6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
